---
title: Programa
lang: es
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(tibble)
library(pander)
```

::: {.grid .course-details .course-details-smaller}

::: {.g-col-6}

### Profesor

- {{< fa user >}} &nbsp; {{< var instructor.name >}}
- {{< fa university >}} &nbsp; {{< var instructor.office >}}
- {{< fa envelope >}} &nbsp; <a href="mailto:{{< var instructor.email >}}">{{< var instructor.email >}}</a>

:::

::: {.g-col-6}

### Información del curso

- {{< fa calendar >}} &nbsp; {{< var course.days >}}
- {{< fa calendar-alt >}} &nbsp; {{< var course.dates >}}
- {{< fa clock >}} &nbsp; {{< var course.time >}}
- {{< fa location-dot >}} &nbsp; {{< var course.location >}}
:::

:::

## Propósito general del curso

Al finalizar el curso los estudiantes conocerán los fundamentos del análisis estadístico diferenciando entre tipos de variables, niveles de medición y formas de distribución. Se espera que los estudiantes sean capaces de diseñar y depurar bases de datos; identificar y definir diferentes tipos de muestreo; aplicar de manera pertinente, estadísticos descriptivos uni y bivariados, utilizar diferentes softwares de análisis estadístico; a partir de los cuáles puedan desarrollar análisis de problemas sociales; contrastar hipótesis de investigación; y elaborar conclusiones integrando fundamentos teóricos con herramientas de análisis estadístico de resultados. Complementariamente se espera que los estudiantes adquieran herramientas que les permitan comunicar resultados de investigación en contextos sociales, profesionales y académicos.

## Competencias

1.  Delimitar, conceptualizar y analizar diversos objetos de investigación social, con especial énfasis en aquellos relacionados con los procesos de transformación del país y Latinoamérica

2.  Manejar diversas estrategias metodológicas de las ciencias sociales.

3.  Manejar un conjunto de herramientas para el procesamiento y análisis de información.

4.  Transmitir los conocimientos derivados de la práctica investigativa, así como aquellos adquiridos durante el proceso formativo.

### Subcompetencias 

- Contribuir a generar conocimiento sociológico en el marco de estudios y/o procesos de investigación donde se articulen creativamente las dimensiones teórica, metodológica y práctica.

- Comunicar los saberes disciplinares de manera pertinente a las características de distintos contextos y audiencias, utilizando diversas estrategias y formatos. 

## Resultados de Aprendizaje

Al finalizar el curso, los estudiantes serán capaces de:

1. Comprender la relevancia del análisis estadístico como herramienta para la investigación sociológica y la comprensión de lo social.

2. Conocer y manejar a nivel inicial las herramientas estadísticas e informáticas necesarias para realizar análisis y descripciones univariadas de datos sociales y sociológicos.

3. Ser capaz de resolver problemas de investigación sociológica simples a partir del uso de técnicas de cálculo, análisis y visualización estadística.

## Saberes / contenidos

**UNIDAD I. Sociología y estadística: algunas vinculaciones y conceptos fundamentales**

1.1. ¿Por qué debe aprender estadística un estudiante o una estudiante de sociología?

- La construcción de conocimiento sociológico y la estadística.

- La estrategia de investigación cuantitativa: estrategia epistemológica, limitaciones y potencialidades.

1.2. La medición en ciencias sociales:

- Medir en ciencias sociales: del constructo teórico al dato estadístico.

- Tipos de variables y niveles de medición.

- La noción de población, muestra, estadístico, parámetro y estimación.

1.3. Datos y bases de datos:

- Las fuentes de información: tratamiento, producción y análisis de datos primarios y secundarios.

- Manejo y depuración de datos y bases de datos.

- Aspectos éticos y posibilidades de investigación en la era de los datos no estructurados.

**UNIDAD II. La descripción de los datos: Medidas de tendencia central, dispersión y posición**

2.1. Medidas de tendencia central

- Supuestos sociológicos tras las medidas de tendencia central. Ejemplos de investigaciones sociológicas relevantes.

- La media, la media recortada, la mediana y la moda. Potencialidades y limitaciones.

2.2. Medidas de dispersión

- Supuestos sociológicos tras las medidas de dispersión. Ejemplos de investigaciones sociológicas relevantes.

- Rango, varianza y desviación típica. Coeficiente de variación. Representaciones gráficas.

2.3. Medidas de Posición

- Distribuciones de frecuencias absoluta, relativa y acumulada.

- Medidas de posición no central: los cuantiles.

- Representaciones gráficas.

**UNIDAD III. La forma de una distribución**

- Noción de función, distribución empírica, teórica y de muestreo. Distribución discreta y distribución continua.

- Características de la forma de una distribución: Asimetría y Curtosis.

- Introducción a la distribución normal. Principales características de la distribución. Uso de la distribución normal. Estandarización y puntaje Z.

- Introducción a otras distribuciones.

**UNIDAD IV. Inferencia estadística univariada: de la estimación puntual al parámetro**

- Tipos de hipótesis y prueba estadística.

- Confianza, potencia y error.

- Estimadores puntuales para medias y proporciones.

- Conceptos de error típico, nivel de confianza y error de estimación.

- La construcción de intervalos de confianza para medias y proporciones.

- Ponderadores y sesgos en estimación de parámetros poblacionales.

## Metodología

La asignatura se desarrollará a través de:

-	Clases lectivas o exposiciones a cargo del profesor, en las que se presentarán las principales temáticas de la asignatura, y en las que los y las estudiantes tendrán la posibilidad de resolver dudas relacionadas con los aspectos teóricos/conceptuales.

-	Un Laboratorio de Análisis de Datos (LAD) a cargo del profesor y Equipo Docente. Se realizarán ejercicios prácticos de procesamiento, análisis e interpretación de resultados mediante diversos softwares de análisis estadístico (Excel, Spss y R). En ellos los y las estudiantes aprenderán a interpretar sociológicamente datos provenientes de múltiples fuentes, visualizar datos en forma gráfica, así como elaborar reportes de resultados.

-	Finalmente, de ser requerido, se realizarán sesiones de ayudantía específicas para reforzamiento de contenidos y del trabajo del Laboratorio de Análisis de Datos.


- Se reforzarán los contenidos con la entrega de material audiovisual y tutoriales

## Evaluación

-	Se realizarán dos controles de los contenidos vistos en clase con el apoyo de alguna lectura bibliográfica. Cada uno de estos controles tendrá una ponderación de 15% (30% en total).

- Durante el transcurso de la asignatura (y en el marco del Laboratorio de Análisis de Datos) se realizará: Un Trabajo de Taller Colectivo (con dos entregas a lo largo del semestre, cada una de las cuales valdrá 20% de la nota final).

## Requisitos de aprobación

-	60% de asistencia obligatoria.

-	Eximición de examen: 

    -	Nota 5.0 o superior.

    -	Cumplir con la asistencia obligatoria.

-	Requisitos para presentación a examen de primera oportunidad:

    -	Nota de presentación igual o superior a 3.5.

    -	Cumplir con la asistencia obligatoria.

-	Para dar el examen en segunda oportunidad no hay requisitos.

-	Nota de aprobación mínima (Escala de 1.0 a 7.0): 4.0.

Las situaciones no cubiertas por este programa se resolverán por las disposiciones existentes en el Reglamento General de Estudios de Pregrado de la Facultad de Ciencias Sociales (Decreto Exento Nº0045106 del 24 de noviembre de 2017). 

Se advierte que todo acto que falte a la ética e integridad académica será sancionado a partir de las medidas establecidas en los reglamentos existentes en la Universidad de Chile, y que velan por asegurar la calidad en la formación académica.

## Palabras Clave 

- Estadística Descriptiva, Estadística Univariada, Medidas de tendencia central, Medidas de dispersión, Distribución Normal.

## Bibliografía Obligatoria

- Blalock, H. (1986). Estadística Social. México D.F.: Fondo de Cultura Económica.

- Ferrando, M. (1999): Socioestadística: Introducción a la Estadística en Sociología. Alianza Editorial.

- Pardo Merino, A., & San Martín Castellanos, R. (2010). Análisis de datos en ciencias sociales y de la salud II. Síntesis, Madrid.

- Cea, D’Ancona, M. (2001). Metodología Cuantitativa. Estrategias y técnicas de investigación social. Síntesis.

- Asún, R. (2006). Medir la Realidad Social: el sentido de la investigación cuantitativa. En: M. Canales (Ed.). Metodologías de Investigación Social (pp. 29-60). Santiago de Chile: LOM.

## Bibliografía Complementaria

- Field, A. (2009). Discovering Statistics Using IBM SPSS. California: SAGE Publications. Disponible online en: http://www.soc.univ.kiev.ua/sites/default/files/library/elopen/andyfield-discovering-statistics-using-spss-third-edition-20091.pdf

- Field, A., Miles, J. y Field, Z. (2012) Discovering Statistics Using R. California: SAGE Publications.

- Boccardo, G. & Ruiz, F. (2019). RStudio para Estadística Descriptiva en Ciencias Sociales. Segunda edición. En línea en: https://bookdown.org/. Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile.

- Ritchey, F. J. (2008). Estadística para las ciencias sociales. McGraw-Hill.

- Stallman, R. (2004). Software libre para una sociedad libre. En línea en: https://www.traficantes.net/. Traficantes de Sueños.

- Wrigth Mills, C. (1975). Empirismo abstracto. En: La imaginación sociológica. México: Fondo de Cultura Económica.

- de Micheaux, P. L., Drouilhet, R., & Liquet, B. (2013). The R software.Fundamentals of Programming and Statistical Analysis. Springer.

- Elousa, P. (2009). ¿Existe vida más allá del SPSS? Descubre R. En Revista Psicothema, vol.21, n° 4, pp. 652-655. Disponible online en: www.ehu.eus/gip/publicaciones/articulos/2009/2.pdf

- González, F. (2019). Big data, algoritmos y política: las ciencias sociales en la era de las redes digitales. Revista Cinta moebio 65: pp. 267-280.

- Grolemund & Wickham (2016). R for Data Science. Disponible en línea en: https://r4ds.had.co.nz/. O’Reilly Media.

- Paradis, E. (2003). R para Principiantes. Francia: Institut des Sciences de l’Évolution. Disponible oline en: https://cran.r-project.org/doc/contrib/rdebuts_es.pdf

- Urdines, F. & Cruz, A. (2019). Analiza R Datos Políticos. Instituto de Ciencia Política de la Universidad Católica de Chile. Disponible en línea: https://arcruz0.github.io/

- Wickham, H. (2015). ggplot2: Elegant Graphics for Data Analysis. Disponible en línea en: https://ggplot2-book.org/. Springer.

## Recursos web

Tutoriales online para uso de software R (en español)

-	https://www.youtube.com/playlist?list=PLccec9enm1CwAZXr9bv92QQ-f_-lVx0ts

-	https://www.youtube.com/watch?v=ox8Q6YGqC3I

-	https://www.youtube.com/watch?v=Sl82PDYjXK0

Cursos en línea para uso de software R (ambos en inglés y con modalidad gratuita y 
pagada)

-	https://www.coursera.org/specializations/jhu-data-science

-	https://www.datacamp.com/courses

Bases de datos de interés

-	http://www.bcentral.cl/index.asp

-	http://www.cepchile.cl/dms/lang_1/home.html

-	http://www.cepal.org/es

-	https://coes.cl/encuesta-panel/

-	http://www.cl.undp.org/

-	http://datos.bancomundial.org/

-	http://www.ilo.org/stat/lang--es/index.htm

-	http://www.ine.cl/

-	http://www.nudesoc.cl/

-	http://stats.oecd.org/

-	http://observatorio.ministeriodesarrollosocial.gob.cl/casen_obj.php

-	https://ourworldindata.org/


