---
title: Trabajos
lang: es
---

# Términos de Referencia Entrega Informe

## Presentación y directrices generales

La presente evaluación tiene por objetivo que las y los estudiantes apliquen de forma integral los contenidos del curso a una temática de interés específica utilizando la base de datos de la Encuesta de Bienestar Social (EBS) 2021, en formato de reporte de investigación breve.

## Cuestiones a considerar

1. El trabajo debe ser realizado en grupos de 5 estudiantes, que deben ser inscritos en el siguiente enlace.
2. Deben elegir uno de los módulos de la Encuesta de Bienestar Social (EBS) 2021, del cual tomarán las variables con las que elaborarán el informe.
3. Se realizará una entrega final tipo reporte de investigación, que se irá construyendo a lo largo del semestre.
4. Se recomienda que elaboren un problema de investigación que trate sobre las características sociales de algún problema actual de la sociedad chilena.
5. El peso de esta evaluación sobre la nota final del curso es del 40%.
6. Se asignará una bonificación por asistencia a los talleres prácticos de R de manera individual.

## Instrucciones para el Informe

### COMPONENTES DEL INFORME

| COMPONENTES                | DETALLE                                                                                                                                                                                                                                                                                       | PUNTAJE |
|----------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|
| Formulación del problema   | Fundamente el interés sociológico que habilita el estudio de la temática elegida (¿Qué se va a estudiar?, ¿Por qué es importante?, ¿Qué se sabe sobre el tema?), utilizando al menos 3 referencias bibliográficas. Además, formule una pregunta y un objetivo general de investigación.        | 1,0     |
| Definición base de datos   | Defina la fuente de información a utilizar indicando el nombre de la base de datos y la institución que la disponibiliza, la población que busca representar el estudio, el procedimiento de muestreo utilizado y el tamaño de la muestra.                                                      | 0,5     |
| Definición variables       | Seleccionar un mínimo de 4 variables para, mediante su estudio, responder a la pregunta de investigación. Para cada variable debe indicar: i) breve descripción, ii) nivel de medición, iii) nombre en la base de datos y fraseo en la encuesta, iv) qué aspecto del fenómeno de interés representa | 2,0     |
| Tablas de frecuencia       | Calcular una tabla de frecuencia (absoluta y relativa) para las variables nominales y ordinales e interpretar. Los cálculos deben ser realizados en R.                                                                                                                                        | 2,0     |
| Medidas de tendencia central | Calcular e interpretar las medidas de tendencia central para las variables intervalares y de razón seleccionadas. Colocarlas en una tabla. Los cálculos deben ser realizados en R.                                                                                                            | 2,0     |
| Medidas de dispersión      | Calcular el rango, la desviación estándar y el coeficiente de variación para las variables intervalares y de razón seleccionadas. Colocarlas en una tabla. Los cálculos deben ser realizados en R.                                                                                            | 2,0     |
| Medidas de posición        | Calcular el valor mínimo y máximo, el cuartil 1 y el cuartil 3 para las variables intervalares y de razón seleccionadas. Colocarlas en una tabla. Los cálculos deben ser realizados en R.                                                                                                      | 2,0     |
| Gráficos                   | Presentar al menos 2 gráficos seleccionando para su construcción aquellas variables más relevantes para el problema de investigación. Los gráficos deben ser realizados en R.                                                                                                                 | 2,0     |
| Conclusiones               | En las conclusiones se deben sintetizar los aspectos más relevantes de los análisis estadísticos ya expuestos, articulando toda la información trabajada. Además, debe reflexionar sobre los límites de su diseño de investigación y señalar posibles ejes de investigación.                       | 2,0     |
| Trabajo en R               | Entregar la carpeta con el Proyecto R, que contenga un archivo .Rproject, y las carpetas input, procesamiento y output. Se evaluará que los códigos utilizados generen las salidas (tablas, gráficos, etc.) que se presentan en el informe.                                                     | 3,0     |

# Aspectos formales

Para la construcción del reporte de investigación, por favor considere:

- El trabajo debe tener una portada que incluya: título, logo de la universidad, nombre de los estudiantes, profesor/a, fecha y ayudantes.
- Debe incluirse un índice. Tablas, referencias y bibliografía utilizada debe presentarse en formato APA.
- La fuente a utilizar debe ser Letra Times New Roman 12, interlineado simple y justificado. Notas a pie de página en tamaño 10.
- El trabajo debe tener una redacción adecuada y sin errores de ortografía.
- Se descontarán hasta 5 décimas sobre la nota final por errores de este tipo.

# Fecha y formato de entrega

El formato de entrega del informe debe ser un documento en formato Microsoft Word (.docx) o formato PDF (.pdf). Fecha de entrega: viernes 19 de julio hasta las 23:59 vía módulo Tareas en plataforma U-Cursos.

- Entregas atrasadas hasta las 0:30 del sábado 20 de julio tendrán 0,5 puntos de descuento sobre la nota final.
- Entregas atrasadas hasta las 23:59 del sábado 20 de julio tendrán 1,0 puntos de descuento sobre la nota final.
- Entregas atrasadas hasta el domingo 21 de julio hasta las 23:59 tendrán 2,0 puntos de descuento sobre la nota final. No serán evaluadas entregas posteriores a esta fecha.

# Sobre plagio

Todos los trabajos se procesan en software para detección de plagio: evidencia de una situación de plagio implica obtención de la nota mínima en la evaluación (1,0) junto con constituirse como causal de reprobación de la asignatura.

# Recomendaciones para la entrega

- Máxima de escritura: una idea por párrafo.
- La idea del párrafo se resume en la primera parte del párrafo.
- Declarar domicilio disciplinar: ej, mencionar la palabra "sociología" en el primer/segundo párrafo.

En caso de tener dudas, no dude en contactar a sus ayudantes respectivos, o bien, vía foro U-Cursos al equipo docente de la asignatura.
